### ISSUE TITLE
Error when browserifying react-select2-wrapper module

### ISSUE THREAD

**Issue by ksmirnoff** [rkit/react-select2-wrapper#1]
I am getting the following error when trying to browserify the wrapper

SyntaxError: node_modules/react-select2-wrapper/src/components/Select2.jsx: Unexpected token (5:19)
  3 |
  4 | export default class Select2 extends React.Component {
> 5 |   static propTypes = {
    |                    ^
  6 |     data: React.PropTypes.array,
  7 |     events: React.PropTypes.array,
  8 |     options: React.PropTypes.object,

**Comment by rkit** [comment]
Please try to upgrade a component, I released an update (0.0.3).
Added compile from es6 to es5.

**Comment by rkit** [comment]
I closed. If you have any problems, let me know.
