### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by nilocoelhojunior** [rkit/react-select2-wrapper#14]
realized the following steps:
git clone, npm i --save-dev, npm run start

I received the error:

`
> react-select2-wrapper@0.3.0 start /home/nilo/Documentos/react-select2-wrapper
> cd examples && node server.js
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
    at Server.listen (/home/nilo/Documentos/react-select2-wrapper/node_modules/webpack-dev-server/lib/Server.js:280:27)
    at Object.<anonymous> (/home/nilo/Documentos/react-select2-wrapper/examples/server.js:18:4)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-select2-wrapper@0.3.0 start: `cd examples && node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-select2-wrapper@0.3.0 start script 'cd examples && node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-select2-wrapper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd examples && node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-select2-wrapper
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/nilo/Documentos/react-select2-wrapper/npm-debug.log
`

any tips?

**Comment by gugahoi** [comment]
You probably shouldn't use `--save-dev` just `npm install`. Do you need this for developing the component or to use it

**Comment by gugahoi** [comment]
Also forgot to mention but the error you seem to be getting is a port conflict. Something else is running on port 3000, maybe another node server?

**Comment by nilocoelhojunior** [comment]
Sorry for my stupidity. I have npm server-json and had not realized that it runs on port 3000. Thanks for the quick response.
