### ISSUE TITLE
Server side rendering fails

### ISSUE THREAD

**Issue by manubamba** [rkit/react-select2-wrapper#22]
The render fails on server side, probably due to the underlying select2

**Comment by rkit** [comment]
Can you show error message?
Please see this [issue](https://github.com/select2/select2/issues/3282), maybe this problem…

**Comment by manubamba** [comment]
TypeError: Cannot read property 'select2' of `undefined`

I'm guessing that the `undefined` is `window`

**Comment by manubamba** [comment]
Thanks for the link! I'll keep a track of the  [issue](https://github.com/select2/select2/issues/3282). Apologies for the duplicate issue.
