### ISSUE TITLE
using the onSelect event, you cannot find the previous select value

### ISSUE THREAD

**Issue by sferoze** [rkit/react-select2-wrapper#23]
I am logged out the event from the onSelect and onChange functions. 

I looked at the object in console and nowhere to be found is the previous value. It only gives data on the new value selected. But how can I get access to the previous value?

**Comment by rkit** [comment]
Maybe via https://github.com/rkit/react-select2-wrapper#access-to-select2 ?
What is your case?

**Comment by afgarcia86** [comment]
This is what I am using.

`changeSelect(select) {
    var self = this
    var newState = {}
    newState[select.currentTarget.name] = helpers.multiSelector(select.currentTarget)
    self.setState(newState)
  }`

and in my helpers.js I have

`multiSelector : function(select) {
  var selectedValues = [];
  for (var i = 0; i < select.length; i++) {
    if (select.options[i].selected) selectedValues.push(select.options[i].value);
  }
  return selectedValues;
}`

**Comment by rkit** [comment]
I closed. If you have any problems, let me know.
