### ISSUE TITLE
add .babelrc to .npmignore 

### ISSUE THREAD

**Issue by nsisodiya** [rkit/react-select2-wrapper#30]
we are trying to use this project but .babelrc creating problem.

Please add .babelrc to .npmignore !
It will be a great help !

**Comment by nsisodiya** [comment]
Also, please update https://github.com/lexich/shallow-equal-fuzzy
to version 0.0.2

**Comment by rkit** [comment]
Ok, today will be release.

**Comment by rkit** [comment]
I released a new version (0.5.2)
