### ISSUE TITLE
React can't find the root component node for data-reactid value...

### ISSUE THREAD

**Issue by dherran** [rkit/react-select2-wrapper#31]
I have a single JS file with the following only:

```
import React, { Component, PropTypes } from 'react'
import ReactDOM from 'react-dom'
import Select2 from 'react-select2-wrapper'

ReactDOM.render(
  <Select2
    multiple
    data={['bug', 'feature', 'documents', 'discussion']}
    options={
      {
        placeholder: 'search by tags',
      }
    }
  />,
  document.getElementById('content')
);
```

This throws the following error on React 0.14.8:

> app.js:1254Warning: React can't find the root component node for data-reactid value `.0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.

I am not loading any other React instances, in fact, this is the only script I have on the page compiled with Browserify.

I am using many other React components and they work fine, however, this one, even when alone (as in the example above) fails.

This error comes specifically from line 89: 

`this.el = $(ReactDOM.findDOMNode(this));`

Any ideas what could be wrong?

I also tried React 15 RC2 and even though I get a different error message, it traces back to exactly the same line.

**Comment by dherran** [comment]
Tried this on a clean setup and it worked fine. It must have been some weird npm module that was causing issues.

**Comment by dherran** [comment]
Ok so after running several tests, I found out that the issue is a nested **node_modules** folder I am getting inside **\node_modules\react-select2-wrapper** after running npm install.

This folder contains:

- fbjs
- react
- react-dom
- whatwg-fetch

This is causing browserify to duplicate ReactJS from **node_modules\react** and **node_modules\react-select2-wrapper\node_modules\react**

If I remove the **node_modules** folder inside **react-select2-wrapper** it works flawlessly.

I might be wrong but could it be that this plugin is calling "React" as dependency instead of a devDependency?

I am on Node 5.7.1.

**Comment by rkit** [comment]
Ok, tomorrow I will do it.

**Comment by rkit** [comment]
Please, try a new version (0.6.1)

**Comment by rkit** [comment]
I closed. Please let me know if you have any problems.
