### ISSUE TITLE
Style of width:auto does not allow the select2 to expand when in a modal...

### ISSUE THREAD

**Issue by joetidee** [rkit/react-select2-wrapper#35]
I have added the folliwing to my Select2 component:

```
<Select2
    ...
    style={{width:'auto'}}
    ...
/>
```

This component is rendered as part of a bootstrap modal dialog. The contents of the dropdow list do not force it to expand fully.

If I use this `width:auto` on a component that is NOT in a modal dialog, it worls ok. Any ideas why this does not work in a modal?

**Comment by rkit** [comment]
I don't even know…  Maybe this help you:
https://github.com/select2/select2/issues/3101 ( `dropdownAutoWidth` )

**Comment by gazpachu** [comment]
How does the dynamic width work? I've been trying different approaches to make it responsive, but the `<input>` always end up defining the final width of the whole thing.

**Comment by rkit** [comment]
@gazpachu I don't know. I never faced such a problem, sorry

**Comment by gazpachu** [comment]
@rkit This is what I mean (see below). It seems they get random widths:

<img width="933" alt="screen shot 2016-11-25 at 17 15 20" src="https://cloud.githubusercontent.com/assets/1721288/20630644/8138f514-b332-11e6-93b3-bae50ba02bc0.png">

**Comment by rkit** [comment]
@gazpachu I guess you should play with css, `style={{width: x'}}` and option `dropdownAutoWidth`

**Comment by gazpachu** [comment]
@rkit setting the `dropdownAutoWidth` option to `true` or `false` doesn't seem to change anything. It doesn't matter if I add a `style={{width: x'}}` cause it gets overwritten with the fixed px width value set by the component.

**Comment by rkit** [comment]
@gazpachu Maybe it is better to create an issue in Select2? This component doesn't add any CSS styles.
