### ISSUE TITLE
Warnings on react-dom 15.2.0

### ISSUE THREAD

**Issue by lee-reinhardt** [rkit/react-select2-wrapper#39]
React DOM 15.2.0 has added warnings for unknown DOM element properties. I noticed one warning from from this library about the `options` and `events` props being passed to the `<select>` element.

I think I can make a quick PR to destructure them before passing `...params` to the `<select>` element.

https://fb.me/react-unknown-prop
![screen shot 2016-07-01 at 3 19 46 pm](https://cloud.githubusercontent.com/assets/980089/16533624/bec196ea-3f9f-11e6-8196-9b687f21eaf8.png)

**Comment by rkit** [comment]
I have fix in v1.0.0, today will be release.

**Comment by rkit** [comment]
I released a new version, with this fix.
