### ISSUE TITLE
Invariant Violation: Select2.render(): A valid ReactComponent must be returned.

### ISSUE THREAD

**Issue by decodeman** [rkit/react-select2-wrapper#4]
I'm using React v0.13.3.  I install react-select2-wrapper from npm.  I follow the example exactly it seems, yet get this error.  Any ideas?

Invariant Violation: Select2.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

```javascript
<Select2
            multiple={false}
            data={[{text: 'Bug', id: 0}, {text: 'Feature', id: 1}, {text: 'Documents', id: 2}, {text: 'Discussion', id: 'UUID'}]}
            options={{
              placeholder: 'search by tags'
            }}/>
```

My imports:
```javascript
import React from 'react';
import Select2 from 'react-select2-wrapper';
```

**Comment by rkit** [comment]
The current version uses React 0.14, v0.0.5 support React 0.13

**Comment by rkit** [comment]
I closed. Let me know if you have any problems.
