### ISSUE TITLE
How to set value of Select2?

### ISSUE THREAD

**Issue by joetidee** [rkit/react-select2-wrapper#41]
I would like to set the value of the Select2 element after it has been rendered, i.e. when a user clicks a button it changes tha value of the Select2 component. How can I do this?

**Comment by rkit** [comment]
As in another component, you need re-render with new value
[examples/src/components/Tags.js#L43-L68](https://github.com/rkit/react-select2-wrapper/blob/master/examples/src/components/Tags.js#L43-L68)

**Comment by Boorj** [comment]
I think, this one could be closed, since it's not an actual issue. Or please describe your problem more precisely.
