### ISSUE TITLE
placeholder is not work

### ISSUE THREAD

**Issue by staceycm** [rkit/react-select2-wrapper#42]
when use the single select    placeholder is not work

**Comment by rkit** [comment]
Please try add empty option
```js
data={
  [ 
    {}, 
    { text: 'bug', id: 1 },
  ]
}
```

**Comment by staceycm** [comment]
Thank you for your answer, it solved the problem of  placeholder, but there is a new problem that when I first select an option, it does not work（My English is not good please do not mind，thank you）





陈萌

------------------------------------------


电子邮件： 13613615880@139.com 






手提电话：  13613615880


公司网站：  www.aspirecn.com



2016年08月10日 星期三

--------------------------------------------------------------------------------




------------------ 原始邮件 ------------------




 
 发件人: Igor Romanov  <notifications@github.com>
 

 
 发送时间: 2016-08-10 18:01:12
 

 
 收件人:rkit/react-select2-wrapper <react-select2-wrapper@noreply.github.com> 

 
 抄送:陈萌 <13613615880@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [rkit/react-select2-wrapper] placeholder is not work (#42)
 



Please try add empty option

 
data={
 [ 
 {}, 
 { text: 'bug', id: 1 },
 ]
}

**Comment by staceycm** [comment]
it is my fault for the new problem, I'm very sorry , and thank you again!







陈萌

------------------------------------------



电子邮件： 13613615880@139.com 






手提电话：  13613615880


公司网站：  www.aspirecn.com



2016年08月10日 星期三

--------------------------------------------------------------------------------




------------------ 原始邮件 ------------------




 
 发件人: "陈萌" <13613615880@139.com>
 

 
 发送时间: 2016-08-10 20:17:31
 

 
 收件人:rkit/react-select2-wrapper <reply@reply.github.com>,rkit/react-select2-wrapper <react-select2-wrapper@noreply.github.com> 

 
 抄送:Author <author@noreply.github.com> 

 
 主题: Re:Re: [rkit/react-select2-wrapper] placeholder is not work (#42)
 



 
    Thank you for your answer, it solved the problem of  placeholder, but there is a new problem that when I first select an option, it does not work（My English is not good please do not mind，thank you）





陈萌

------------------------------------------


电子邮件： 13613615880@139.com 






手提电话：  13613615880


公司网站：  www.aspirecn.com



2016年08月10日 星期三

--------------------------------------------------------------------------------

 
 ------------------ 原始邮件 ------------------ 
 
 发件人: Igor Romanov  <notifications@github.com> 
 发送时间: 2016-08-10 18:01:12 
 收件人:rkit/react-select2-wrapper <react-select2-wrapper@noreply.github.com> 
 抄送:陈萌 <13613615880@139.com>,Author <author@noreply.github.com> 
 主题: Re: [rkit/react-select2-wrapper] placeholder is not work (#42) 
 
 Please try add empty option

 
data={
 [ 
 {}, 
 { text: 'bug', id: 1 },
 ]
}

**Comment by staceycm** [comment]
it is my fault for the new problem , I'm very sorry , and thank you again!









陈萌

------------------------------------------


电子邮件： 13613615880@139.com 






手提电话：  13613615880


公司网站：  www.aspirecn.com



2016年08月10日 星期三

--------------------------------------------------------------------------------




------------------ 原始邮件 ------------------




 
 发件人: Igor Romanov  <notifications@github.com>
 

 
 发送时间: 2016-08-10 18:01:12
 

 
 收件人:rkit/react-select2-wrapper <react-select2-wrapper@noreply.github.com> 

 
 抄送:陈萌 <13613615880@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [rkit/react-select2-wrapper] placeholder is not work (#42)
 



Please try add empty option

 
data={
 [ 
 {}, 
 { text: 'bug', id: 1 },
 ]
}

**Comment by rkit** [comment]
You're welcome )
