### ISSUE TITLE
component update when value not mutated

### ISSUE THREAD

**Issue by DiesIrae** [rkit/react-select2-wrapper#43]
Hi,

If I attach a component `value` to this.state.items, and I do the following, it doesn't updates :

```
const items = this.state.items;
items.push(newItem);
this.setState({items};
```

And if I just add

```
items = _.clone(items);
```

before setState, it works. Is it normal? Seems misleading.

**Comment by rkit** [comment]
Oh, yes, there is bug. I'll try fix soon. Thanks for the report.

**Comment by rkit** [comment]
Please, try a new beta release (1.0.1-beta1).

**Comment by DiesIrae** [comment]
It works perfectly, thank you.
