### ISSUE TITLE
Limiting the number of selections (ex: maximumSelectionLength=2)

### ISSUE THREAD

**Issue by khoandse** [rkit/react-select2-wrapper#44]
Is there any way to pass option "maximumSelectionLength" into the component?

Select2's way: select2.github.io/examples.html#multiple-max

I tried your way: https://github.com/rkit/react-select2-wrapper#properties
But it didn't work.

**Comment by rkit** [comment]
You shoud use `options`.
Example:
```js
<Select2
  multiple
  data={['bug', 'feature', 'documents', 'discussion']}
  options={
    {
      maximumSelectionLength: 2,
      placeholder: 'search by tags',
    }
}
/>
```
