### ISSUE TITLE
Question about Object.assign usage

### ISSUE THREAD

**Issue by RebootJeff** [rkit/react-select2-wrapper#45]
I'm curious about this [piece of code](https://github.com/rkit/react-select2-wrapper/blob/master/src/components/Select2.js#L154) in the render function: 
```javascript
const { data, value, ...props } = this.props;
const params = Object.assign(props);
```
Why is `Object.assign` used here? Is it to make sure `params` only gets `props`'s "own" properties? What's an example of the `Object.assign` line coming in handy?

**Comment by rkit** [comment]
This line is wrong. I will fix it. `Object.assign` here is useless.
Thanks!
