### ISSUE TITLE
Doesn't listen property changes for option parameter

### ISSUE THREAD

**Issue by acierto** [rkit/react-select2-wrapper#46]
Create wrapper component, which contain something like that:

`...
render()  { 
return <Select2
                            defaultValue={this.state.selectedValue}
                            data={this.props.selectData}
                            onChange={(e) => this.onSelection(e.target.value)}
                            options={{disabled: this.props.disabled}}
                        />
}
`
Then create some toggler, which will change disabled from false to true. Select2 renders the first state of disabling correctly, but afterwards ignores updates of this property.

**Comment by rkit** [comment]
Please check new release 1.0.2.
Thanks for PR and bug report.
