### ISSUE TITLE
When Selected Item Text is too long, not hide extra Word 

### ISSUE THREAD

**Issue by gebin** [rkit/react-select2-wrapper#50]
> .select2-container .select2-selection--single .select2-selection__rendered {
>     display: block;
>     padding-left: 8px;
>     padding-right: 20px;
>     overflow: hidden;
>     text-overflow: ellipsis;
>     white-space: nowrap;
> } 

![image](https://cloud.githubusercontent.com/assets/2951334/18948657/8a182456-866a-11e6-9ea4-2d5c375271cd.png)

**Comment by rkit** [comment]
Sorry for the delay, but this issue not related to this component, you should look at CSS styles.
