### ISSUE TITLE
Selects first option automatically

### ISSUE THREAD

**Issue by farhan687** [rkit/react-select2-wrapper#53]
I am using tags true when I try to create a new tag, Select2 automatically choose the first option though it is not executing onchange event but it should be empty if I didn't select anything already.

![animation 1](https://cloud.githubusercontent.com/assets/6059027/19553418/de5bb556-96d1-11e6-9c9e-10691d9e931f.gif)

other than this wrapper works pretty well, thanks a lot for creating such wrapper, it saved my lot of time.

**Comment by farhan687** [comment]
Implement detail:

```js
<Select2
                multiple={false}
                data={ ['test', 'test1', 'cool'] }
                value={this.state.selectedType}
                options={{
                  placeholder: 'Choose or create a new type',
                  tags: {true}
                }}
                onChange={this.onTypeSelection}
              />
```

**Comment by rkit** [comment]
> thanks a lot for creating such wrapper, it saved my lot of time

You are welcome!

Please try following code:

```js
<Select2
  multiple={false}
  data={ ['', 'test', 'test1', 'cool'] }
  value={this.state.selectedType}
  options={{
    placeholder: 'Choose or create a new type',
    tags: true,
    allowClear: true,
  }}
  onChange={this.onTypeSelection}
/>
```

**Comment by farhan687** [comment]
Thanks @rkit, it works.
