### ISSUE TITLE
How can i add extra field on this select wrapper form?

### ISSUE THREAD

**Issue by Sebszty** [rkit/react-select2-wrapper#57]
Now i can print id & text, i want to store and print one more value "extra". 
If it is possible?

 data:[
            {id:0,text:"asda",extra:"one"},
            {id:1,text:"adasdas",extra:"two"},
        ],

**Comment by rkit** [comment]
If you about data-* attributes:
```js
{ text: 'documents', id: 3, 'data-prop': 'val' },
```
