### ISSUE TITLE
Document which verison of select2 is being wrapped.

### ISSUE THREAD

**Issue by joetidee** [rkit/react-select2-wrapper#58]
Could you include somehwere what equivalent version of Select2 is included in this package?

**Comment by rkit** [comment]
I don't quite understand, please could you clarify…

**Comment by joetidee** [comment]
I mean, is the react-select2-wrapper a wrapper for the original select2 package and, if so, do you track the version of that package? It would be useful to know because if, for example, select2 upgrade their package and you haven't upgraded yours with the same functionality, then the developers using your package will know not to expect certain features, or expect certain things not to be working.

**Comment by rkit** [comment]
According to the [specified rule](https://github.com/rkit/react-select2-wrapper/blob/master/package.json#L31): >= 4.0.0 and < 5.0.0 (Latest version 4.0.3)
