### ISSUE TITLE
react-select2-wrapper error

### ISSUE THREAD

**Issue by jiangtong** [rkit/react-select2-wrapper#60]
Module not found: Error: Cannot resolve module 'expose' in /Users/jiangtong/Desktop/beautyandcar/sunmnet_bigdata_web/node_modules/react-select2-wrapper/lib/components
 @ ./~/react-select2-wrapper/lib/components/Select2.js 47:14-31

**Comment by rkit** [comment]
It seems to me that a problem with your webpack configuration
see: https://github.com/webpack-contrib/expose-loader
