### ISSUE TITLE
How to dynamically load translations?

### ISSUE THREAD

**Issue by mfdolarea** [rkit/react-select2-wrapper#64]
Which is the proper way to apply a different translation file (eg: i18n/es.js) ?

**Comment by rkit** [comment]
As for as I know, you should include the translation (`import 'select2/dist/js/i18n/es`) and to change language through `options.language`

**Comment by mfdolarea** [comment]
Yep, that's it! Thanks

**Comment by fsabreu** [comment]
@rkit I'm with same problema. Can you give an example?

Thanks
