### ISSUE TITLE
app.js:357 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by jhayiwg** [rkit/react-select2-wrapper#68]
Hello,

Thanks for this component. I`m trying to implement this to my project but I`m seeing this warning.

I`m using react : 15.0.1

**Comment by rkit** [comment]
Hello. It will soon be fixed.

**Comment by aberonni** [comment]
Hi any update on this? Can we leave the issue open until it is fixed?
