### ISSUE TITLE
Add styles to node module

### ISSUE THREAD

**Issue by czerasz** [rkit/react-select2-wrapper#7]
Could you add styles to the package?

**Comment by rkit** [comment]
Ok. I'll do it today.

**Comment by rkit** [comment]
I released **v0.0.10**
https://github.com/rkit/react-select2-wrapper#themes

```js
import 'react-select2-wrapper/css/select2.css';
// or
import 'react-select2-wrapper/css/select2.min.css';
```

**Comment by rkit** [comment]
I closed. Let me know if you have any problems.

**Comment by czerasz** [comment]
Thx @rkit, works great!
