### ISSUE TITLE
Can't set class in dropdown container

### ISSUE THREAD

**Issue by simonpay** [rkit/react-select2-wrapper#71]
I'm trying to set a class in the generated select2 dropdown container via the  `dropdownCssClass` option.

E.g.

```
<Select2
  ...
  options={{
    dropdownCssClass: 'my-class-name',
  }}
/>
```

I read that this option requires the full version of select2 to work.

I'm able to get it working by changing the code on line 29 of /react-select2-wrapper/lib/components/Select2.js from:

`require('select2');`

to:

`require('select2/dist/js/select2.full');`

Is there any way I can tell react-select2-wrapper to use the full version without hacking the package?

Thanks

**Comment by simonpay** [comment]
Hi,

Any help on this would be appreciated.

Thanks

**Comment by rkit** [comment]
Do you use Webpack?

**Comment by rkit** [comment]
Please see this issue #8

**Comment by simonpay** [comment]
Thanks for the reply.

I'm not using Webpack. Are there other options for me?

**Comment by simonpay** [comment]
Thanks for the pointer in https://github.com/rkit/react-select2-wrapper/issues/8. 

Based on this I used [pathmodify](https://www.npmjs.com/package/pathmodify) to rewrite the path for select2 to the full version (I'm using browserify):

The relevant portion of my gulp task looks like this:

```
  ...
  return browserify('./src/app.js')
    /**
     * Use pathmodify to replace the reference to select2 with
     * the full version of the lib to support adding a class to
     * the generated dropdown markup.
     */
    .plugin(pathmodify, {
      mods: [
        pathmodify.mod.id('select2', 'select2/dist/js/select2.full'),
      ],
    })
    ...
```
