### ISSUE TITLE
hierarchy not  support ? 

### ISSUE THREAD

**Issue by tezrik** [rkit/react-select2-wrapper#74]
Hi, I'm having a problem displaying the hierarchy.

    dataSelect2 : [
            {
                text : '1',
                children : [
                    {
                        text : '2',
                        children : [
                            {text : '5', id : 5},
                            {text : '6', id : 6}

                        ]
                    },
                    {text : '4', id : 4}
                ]
            },
            {text : '7', id : 7},
            {text : '8', id : 8}
        ]

With this data, only the first 2

**Comment by rkit** [comment]
```
dataSelect2 : [
        {
            text : '1',
            children : [
                {
                    text : '2',
                    children : [
                        {text : '5', id : 5},
                        {text : '6', id : 6}

                    ]
                },
                {text : '4', id : 4}
            ]
        },
        {text : '7', id : 7},
        {text : '8', id : 8}
    ]
```
