### ISSUE TITLE
Select2 full

### ISSUE THREAD

**Issue by nicolas-t** [rkit/react-select2-wrapper#8]
Hi,

Any way to load select2.full instead of select2 ? its adds the ability to add a className to the dropdown :  
with `options.dropdownCssClass` 

Best regards,

**Comment by rkit** [comment]
Hi, I'll think about it.
If you are using the webpack, you can do so:
```js
resolve: {
  alias: {
    'select2 ': 'select2/dist/js/select2.full',
  },
},
```

**Comment by nicolas-t** [comment]
It works, thanks, I used this syntax : 

```
resolve: {
  alias: {
    'select2': 'select2/dist/js/select2.full.js',
  },
},
```

(removed the space after `select2 ` and added `.js` at the end of path)

**Comment by DiesIrae** [comment]
Hi,

I'm on Meteor so it's complicated to access the webpack layer. It would be great to have this feature!

Thanks.
